### ISSUE TITLE
Error while building SMASH with ROOT on the System?

### ISSUE THREAD

**Issue by MaxWiest** [smash-transport/smash#32]
Hi all,
we have tried to build the model, running into an issue, which seems to be related to something in the code. As far as the configuration of pythia and eigen goes, it seems to work fine (although we had to download pythia 8.303 from pythia's site, because the link in the instruction has not worked at the time we tried to make it).

We used 
git clone https://github.com/smash-transport/smash 
to get the repository and set up eigen and pythia as described in the README file. Those programs did not complain.

After some trouble with the exact cmake command,

cmake -DCMAKE_PREFIX_PATH=/home/user/eigen-3.4.0/ ..  .. -DPythia_CONFIG_EXECUTABLE=/home/user/pythia8303/bin/pythia8-config

produced the build files in the folder we made via mkdir smash/build. Is this command correct? The ReadMe is a bit confusing for us, as it wants to go to the folder smash/build/ while setting up eigen before this folder has been made in the next step setting the pythia path.

We get the error on the 'make' command, related to the "experimental" class after roughly 17 to 25 % of building:
 
In file included from /home/user/root/include/TString.h:29,
                 from /home/user/root/include/TNamed.h:26,
                 from /home/user/root/include/TDirectory.h:24,
                 from /home/user/root/include/TDirectoryFile.h:25,
                 from /home/user/root/root/include/TFile.h:28,
                 from /home/user/root/smash/src/include/smash/rootoutput.h:18,
                 from /home/user/root/smash/src/include/smash/experiment.h:50,
                 from /home/user/root/smash/src/experiment.cc:10:
/home/user/root/include/ROOT/RStringView.hxx:32:37: error: ‘experimental’ in namespace ‘std’ does not name a type
   32 |    using basic_string_view = ::std::experimental::basic_string_view<_CharT,_Traits>;
      |                                     ^~~~~~~~~~~~
/home/user/root/include/ROOT/RStringView.hxx:35:12: error: ‘basic_string_view’ does not name a type
   35 |    typedef basic_string_view<char> string_view;
      |            ^~~~~~~~~~~~~~~~~

We use ROOT 6 (6.24/02), so is it possible this error might be somehow ROOT version dependent? 

System: Ubuntu 20.04.03 LTS, focal on WSL 2. The same issue persists on a system with ROOT 6 and Mint 20.2 MATE.

In case you need any further information, please let us know.

Best regards,

Mateusz and Max

**Comment by gabriele-inghirami** [comment]
> We use ROOT 6 (6.24/02), so is it possible this error might be somehow ROOT version dependent?

The current public version was tested with ROOT 6.22.08, compiled from sources.
The next upcoming public version is currently tested with ROOT 6.24.06, again compiled from sources.
With ROOT versions >= 6.24, it is **necessary** to pass to `cmake` the option:
`-DCMAKE_CXX_STANDARD=14`
However, I stress that ROOT 6.24.x has been tested _only_ in the current development branch and it is not guaranteed to work with SMASH 2.0.2.

**Comment by gabriele-inghirami** [comment]
> System: Ubuntu 20.04.03 LTS, focal on WSL 2.

Do you want to use SMASH in a virtual GNU/Linux environment under Windows? If you are also using Docker, I can provide you with a Dockerfile for the stable version that _should_ work (with some performance loss compared to a true native GNU/Linux environment).

**Comment by Koniu122** [comment]
Hi all,
As Max mentioned before I'm trying to build SMASH on Mint 20.2 MATE with ROOT 6.24.06. I've added suggested `-DCMAKE_CXX_STANDARD=14` flag (which solved previous issue with experiment.cc), also trying with ROOT enabled or disabled (by` -DUSE_ROOT=OFF`), however each time I run into an issue with hepmcinterface.cc:

/home/koniu/Software/smash/src/hepmcinterface.cc:234:11: warning: multi-character character constant [-Wmultichar]
  234 |   return 1'000'000'000 + az.second * 10'000 + az.first * 10;
      |           ^~~~~
/home/koniu/Software/smash/src/hepmcinterface.cc:234:19: warning: character constant too long for its type
  234 |   return 1'000'000'000 + az.second * 10'000 + az.first * 10;
      |                   ^~~~~~~~~~~~~~~~~~~~~~
/home/koniu/Software/smash/src/hepmcinterface.cc: In member function ‘int smash::HepMcInterface::ion_pdg(const AZ&) const’:
/home/koniu/Software/smash/src/hepmcinterface.cc:234:11: error: expected ‘;’ before '\x303030'
  234 |   return 1'000'000'000 + az.second * 10'000 + az.first * 10;
      |           ^~~~~
      |           ;
/home/koniu/Software/smash/src/hepmcinterface.cc:234:16: error: expected ‘;’ before numeric constant
  234 |   return 1'000'000'000 + az.second * 10'000 + az.first * 10;
      |                ^~~
      |                ;
/home/koniu/Software/smash/src/hepmcinterface.cc:234:11: warning: statement has no effect [-Wunused-value]
  234 |   return 1'000'000'000 + az.second * 10'000 + az.first * 10;

Do you have any idea what might be the problem? Seems like compiler does not like those` ' `placed in return value. However as far as I know this problem wasn't present in any of Max's attempts, which make me bit confused.
cmake flags (with root on and off) look as follows:

`cmake -DCMAKE_PREFIX_PATH=~/Software/Eigen/eigen-3.4.0 .. -DPythia_CONFIG_EXECUTABLE=~/Software/Pythia/pythia8303/bin/pythia8-config DCMAKE_CXX_STANDARD=14 .. -DCMAKE_CXX_COMPILER=g++ -DUSE_ROOT=OFF`

`cmake -DCMAKE_PREFIX_PATH=~/Software/Eigen/eigen-3.4.0 .. -DPythia_CONFIG_EXECUTABLE=~/Software/Pythia/pythia8303/bin/pythia8-config DCMAKE_CXX_STANDARD=14 .. -DCMAKE_CXX_COMPILER=g++`

Best regards,

Mateusz (and Max)

**Comment by gabriele-inghirami** [comment]
If what you copied and pasted is exactly the command that you used, there is a missing "-" character before `DCMAKE_CXX_STANDARD=14`, so that it is not recognized as an option and standard 14 is not used.
Please, try with:
`cmake -DCMAKE_PREFIX_PATH=~/Software/Eigen/eigen-3.4.0 .. -DPythia_CONFIG_EXECUTABLE=~/Software/Pythia/pythia8303/bin/pythia8-config -DCMAKE_CXX_STANDARD=14 -DCMAKE_CXX_COMPILER=g++ -DUSE_ROOT=OFF`
(I added the "-" and removed the duplicated path to the sources "..")

**Comment by gabriele-inghirami** [comment]
Hi! Is the problem solved? If this is the case, please, close the issue.
Otherwise, I am available for further support. 

Thank you!

Gabriele

**Comment by Koniu122** [comment]
Hi,
Yes problem is solved. Sorry, forgot to confirm that, my apologies.
Best regards,
Mateusz

wt., 21 gru 2021, 17:00 użytkownik Gabriele Inghirami <
***@***.***> napisał:

**Comment by gabriele-inghirami** [comment]
OK, thank you!

Merry Christmas and best regards!
G.
